### ISSUE TITLE
Replace `DOMParser` with `template` + `innerHTML` to avoid memory leak

### ISSUE THREAD

**Issue by JounQin** [kmck/rehype-dom#23] opened 2024-02-24 13:01 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-dom-parse

### Steps to reproduce

https://stackoverflow.com/questions/56451731/dom-parser-chrome-extension-memory-leak

### Expected behavior

No memory leak

### Actual behavior

I just noticed this issue from https://twitter.com/DIYgod/status/1761065494185156663

**Comment by ChristianMurphy** [comment] 2024-02-24 13:45
Thanks for raising an issue @JounQin! 🙇 
Is this something you are raising because you think it may be a potential issue? Or have you seen it cause a memory leak in practice?
Would you be able to share a reproducible example of the issue in `rehype-dom`?
Do you believe this is a bug in `rehype-dom` or an issue in Chromium?

---

I ask because the StackOverflow issue https://stackoverflow.com/questions/56451731/dom-parser-chrome-extension-memory-leak, is all over the place.
It references Firefox (determined to be not an issue https://bugzilla.mozilla.org/show_bug.cgi?id=1646237), JSDom (resolved in https://github.com/jsdom/jsdom/issues/2722), and Chromium (specific to when video is being parsed, and unconfirmed https://issues.chromium.org/issues/254330164)

The Twitter post referenced https://twitter.com/DIYgod/status/1761065494185156663

> RSSHub Radar has a memory leak bug that has existed for several years. The cause has never been found. The entire warehouse code has been rewritten and it still cannot be solved. It is very painful. Today I finally caught it. The culprit is Chrome's native DOMParser.
>
> The reference to the DOM returned by DOMParser will exist permanently in the memory and cannot be cleared manually or by GC. In the end, more and more memory will explode.

(translated to English)

Appears to come from parsing XML rather than HTML and also hasn't been reported to or confirmed by the Chromium team.

**Comment by JounQin** [comment] 2024-02-24 14:50
@ChristianMurphy 

> Is this something you are raising because you think it may be a potential issue?

Indeed.

> Would you be able to share a reproducible example of the issue in rehype-dom?
> Do you believe this is a bug in rehype-dom or an issue in Chromium?

I believe it should be an issue of Chrome. And we can avoid this potential issue by just replacing the usage of `DOMParser` included by #19.

And it's very common to use `template`, see also https://github.com/syntax-tree/hast-util-from-html-isomorphic/issues/2

> Appears to come from parsing XML rather than HTML and also hasn't been reported to or confirmed by the Chromium team.

![image](https://github.com/rehypejs/rehype-dom/assets/8336744/81534649-748c-43ae-acb2-d48f9fc003dc)

It's parsing `html`, not `xml`.

**Comment by wooorm** [comment] 2024-03-06 17:14
#19 already landed. `template` is already used for fragments. `DOMParser` is used for *entire* documents. I don’t think there’s an alternative for that?

**Comment by JounQin** [comment] 2024-03-06 17:21
@wooorm 

#19 is always using `DOMParser`, not `template`, sorry. 😅

~~Is that possible to use `iframe` for document instead?~~

I realize that we shouldn't use `iframe` to avoid unnecessary requests.

**Comment by wooorm** [comment] 2024-03-07 08:38
Ah, I can’t keep track.
Well, #18 explains it. Safety is more important than a bug in v8, which they should fix?

**Comment by JounQin** [comment] 2024-03-07 08:43
@wooorm 

`template` will not `send HTTP request` at the same time? That's why I raised https://github.com/syntax-tree/hast-util-from-html-isomorphic/issues/2 to discuss which API (`template` vs `DOMParser`) should be preferred, I hope we can be constant between our libraries.

**Comment by wooorm** [comment] 2024-03-07 08:55
I don’t understand what you want.
In this issue you want `template`.
Before you wanted `DOMParser`.
What do you propose?

Please keep in mind that `<template>` cannot parse entire documents. And `DOMParser` needs a small workaround for fragments. And we need to support both.

**Comment by JounQin** [comment] 2024-03-07 09:25
> I don’t understand what you want. In this issue you want `template`. Before you wanted `DOMParser`. What do you propose?
> 
> Please keep in mind that `<template>` cannot parse entire documents. And `DOMParser` needs a small workaround for fragments. And we need to support both.

Yes, sorry for the confusion, before I know there could be a memory leak I'd prefer `DOMParser`, but now I'd prefer to use `template` for `Fragment`, not `document`.

So my proposal would be change to use `template` for `Fragment` while keep using `DOMParser` for `document`.

If you agree, I'd like to raise a PR.

**Comment by remcohaszing** [comment] 2024-03-07 09:28
Based on the last comment I’d say go for it :+1:

**Comment by wooorm** [comment] 2024-03-07 13:00
I'm okay with that, **if** there are no HTTP requests sent for images, and scripts don't run!

**Comment by JounQin** [comment] 2024-03-07 13:13
Sure, that's https://github.com/syntax-tree/hast-util-from-html-isomorphic/issues/2 talking about.

**Closed as completed** 2024-09-17 11:37 UTC
Labels: 💪 phase/solved
